### ISSUE TITLE
Add QC PDFs to Shiny app

### ISSUE THREAD

**Issue by piersond** [lter/lterwg-som-shiny#19]
Bring HMGZD_notes PDFs from SOM GDrive into Shiny app. Initial idea is to implement this through a new tab that provides a list of links to the PDFs. Further idea, we may want to include a widget on the page to help users find the right PDF using either google_dir, site_name or location name.

**Comment by wwieder** [comment]
I'm not sure the qc plots are needed, but maybe the HMGZD_notes?  What about linking the notes.pdf on the data_summary -- by site tab?

**Comment by piersond** [comment]
@wwieder that does look like a good spot!...and I think I see a fairly easy route to make it happen. Pulling in the QC html files as well will not take more than a few minutes extra work. Is there a larger concern for providing those QC files to users? 

@piersond code implementation: `filter server data_tbl() by location_name --> pull unique(google_dir), check n=1, grab PDF with paste0`

**Comment by wwieder** [comment]
no concern on providing the qc files, but we aren't consistently producing them when we homog sites, so you'll be hit or miss on their presence.

**Comment by piersond** [comment]
Completed
