### ISSUE TITLE
Functionality from shiny

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som-shiny#2]
Here's a list of functionality we'd like to bring into the SOM-shiny ap.  
_[Note, each of these could be a differ issue, if it's helpful?]_

1. plotting univariate data summaries of profile data, grouped by site, googleID, or other location data (typically strings).
2. bivariate plots of numeric data
3. Maps showing locations of where data are available for single variables.
4. Ability to filter data by X:  (network, experiments, depth, etc).
5. With all of the above it would be cool to also color points by particular filters (either as numerics or strings).
6. Download a smaller dataset for users to work with 

The shell of this functionality may be close to in place (with basic R scripts from @piersond)?

**Comment by piersond** [comment]
Alpha version of the app has functionality for items, 1, 2, 4, 6. Item number 5 (color and symbology) is in the works for the current app, but we may need a separate app for the maps.

**Comment by wwieder** [comment]
@piersond this is awesome
Few questions, is there any way to use characters (e.g. network) for colors in the x-y plots or maps?  Alternatively, how hard would it be to make symbology more distinct instead?    These are minor issues and not worth a ton of time.

**Comment by piersond** [comment]
@wwieder the character columns follow the numeric columns in the "Color" drop down list. Select network and see if works, or easier, just start typing "network" in the box. 
![image](https://user-images.githubusercontent.com/36753480/64274830-0f46fd80-cef9-11e9-8129-6c90af15ebc6.png)

Your question points at a bigger fix we may need for the whole app: how do we refine the list of variable options and table columns so it's not overwhelming...?

**Comment by wwieder** [comment]
Ah, you're right.  I was trying to do this in the map, where it was throwing an error.  This can be a one off, however, that we script for the database paper anyway.

Is NutNet not in this tarball right now?

**Comment by wwieder** [comment]
Does it get too cluttered to make additional sliders to mask the data (similar to depth) so we can more easily mask out organic soils or other fields of interest? How hard would it be to add an additional (generic) slider next to depth?

**Comment by piersond** [comment]
@wwieder what else is on the wish list? I'm going to start tidying up the smaller details for what's currently in place, but if you have more ideas for the app let's do it! @nathanhwangbo is ready for to start on the next component, whatever it is...

**Comment by wwieder** [comment]
Functionality in the app is super powerful! Only idea I have would be the option to report the mean value for an analyte for a site, instead of the number of observations?  I'd rate this as lower priority, however, than getting calculation and additional data (C:N and climate) up for the tarball.

**Comment by piersond** [comment]
Closing this issue. Best to give future enhancements there own issue as I might lose track of them here. I've made a new issue for the stats calculations.
