### ISSUE TITLE
NutNet Depth

### ISSUE THREAD

**Issue by shiny-som** [lter/lterwg-som-shiny#23]
Name: Will Wieder
 Email: wwieder@ucar.edu
 Were NutNet samples collected at consistent depths?  If so, let's get this in the tarball so we can get stock_calc values!

**Comment by srearl** [comment]
http://www.nutnet.umn.edu/soil-sampling

**Comment by srearl** [comment]
new tarball on oct 13 that I believe reflects the correct depths for nutnet - @wwieder please confirm

**Comment by wwieder** [comment]
Yes, these were added and now in the tarball
