### ISSUE TITLE
page name in web browser is strange

### ISSUE THREAD

**Issue by brunj7** [lter/lterwg-som-shiny#33]
Small detail but making sure it is not a bigger problem:  the page name is `<a href...` which is not normal for a shiny app. I checked the header and it seems there are 2 title tags: 
 
```html
<title>
  | <a href="https://lter.github.io/som-website/" style="color:white">LTER SOM</a>
  | </title>
  | <title>LTER SOM Database</title>
  |  
```

Coming from: https://github.com/lter/lterwg-som-shiny/blob/a13b1316c93e2159a68460fa33c946bfa4df5627/shiny_SOM/ui.R#L65-L66

just commenting these lines out solve the problem. Not sure why it was introduced in the first place, so I let @piersond to check first.

**Comment by piersond** [comment]
I recently noticed the title problem as well. The problem arose from when I added a linked "LTER SOM" in the header to our project website. I'll poke around and see if there's another way to link that text.

**Comment by piersond** [comment]
Fixed. Shiny: `navbarPage()` has a separate option to direct set `windowTitle = "LTER SOM Database"`. Fix will go live with next app update.
