### ISSUE TITLE
Outlier

### ISSUE THREAD

**Issue by shiny-som** [lter/lterwg-som-shiny#36]
Name: Emily Kyker-Snowman
 Email: emilykykersnowman@gmail.com
 In this entry, lyr_soc and lyr_n_tot have the same value and I think the n value is wrong (3x higher than any other n measurement):

294938	
NWT_SnowFence_soils_2015	WW_Copy_soils_pH_2015.csv

**Comment by wwieder** [comment]
the soil C data were also provided for soil N in this sample.  I removed this error in the raw data being homogenized, new data are ready for the tarball.
