### ISSUE TITLE
Tabs on shiny page

### ISSUE THREAD

**Issue by wwieder** [lter/lterwg-som-shiny#4]
Can we get some basic summary tabs that aren't interactive, but that are updated with the tarball on the top of the shiny page?  These could include summary tables, maps (colored by network) etc?

**Comment by wwieder** [comment]
@piersond can you add basic information from the key-key as a tab that people can look at to find information about data?

**Comment by piersond** [comment]
In the works, coming in next Shiny app update

**Comment by wwieder** [comment]
looks like this is done now
